### ISSUE TITLE
Orion-LD Deployment Fails

### ISSUE THREAD

**Issue by dalxds** [FIWARE/load-tests#84]
Following the config files for deployment, I've created a new Helm Chart that has orion-ld, mongodb and timescale as deps.

The values.yaml of the Chart can be seen below:

``` yaml
mongodb:
  architecture: standalone
  useStatefulSet: true
  auth:
    enabled: false
  tls:
    enabled: false
    autoGenerated: false
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

orion:
  broker:
    troe:
      enabled: true
      dbHost: timescale
      dbUser: postgres
      dbPort: 5432
      dbPassword: gmruukctFW1j93e5r7RI5ZIwLNvG5oxE
    mutexPolicy: none
    reqPoolSize: 32
    db:
      hosts:
        - neptune-eew-mongodb-0.neptune-eew-mongodb.default.svc.cluster.local
    logging:
      level: DEBUG

timescaledb-single:
  replicaCount: 1
  backup:
    enabled: false
  podManagementPolicy: Parallel
  serviceAccount:
    create: false
  
```

I followed the guide in the timescaledb charts to [create the secrets](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#creating-the-secrets) and then used [this](https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single#connecting-to-timescaledbs) command to decrypt and use the db password.

However, Orion-LD failes to connect to the timescale-db.
Logs from the broker can be found below:
``` 
time=2021-08-31T10:05:07.842Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[212]:mongoConnect | msg=Successful connection to database
time=2021-08-31T10:05:07.843Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=MongoGlobal.cpp[245]:mongoInit | msg=Connected to mongo at neptune-eew-mongodb-0.neptune-eew-mongodb.default.svc.cluster.local:orion
2021/08/31 10:05:07.0848: [    1]:  WARNING:       mongoc: Falling back to malloc for counters.
time=2021-08-31T10:05:07.857Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=pgDatabasePrepare.cpp[49]:pgDatabasePrepare | msg=Database Error (unable to connect to postgres - connection/status: 0x5574573d6700/1)
time=2021-08-31T10:05:07.857Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=troeInit.cpp[41]:troeInit | msg=Basic Postgres Problem - Temporal Representation of Entities is not possible
time=2021-08-31T10:05:07.857Z | lvl=FATAL | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=orionld.cpp[1015]:main | msg=Database Error (unable to initialize the layer for Temporal Representation of Entities)
```

Any help would be appreciated.
Thanks!
